color0 #5e3f3d
color1 #ffb4ab
color2 #ffb3ae
color3 #ffb3ae
color4 #ffb779
color5 #ffb3ae
color6 #ffb3ae
color7 #fedad7
color8 #ae8784
color9 #ffb4ab
color10 #ffb3ae
color11 #ffb3ae
color12 #ffb779
color13 #ffb3ae
color14 #ffb3ae
color15 #fedad7

cursor                #fedad7
cursor_text_color     #000000
background            #000000
foreground            #fedad7
selection_foreground  #e8bcb9
selection_background  #5e3f3d
active_border_color   #ffb3ae
inactive_border_color #4f3230
url_color             #ffb3ae

active_tab_foreground   #68000b
active_tab_background   #ffb3ae
inactive_tab_foreground #e8bcb9
inactive_tab_background #4f3230
cursor_trail_color      #e8bcb9
