include home/liam/.config/kitty/themes/macchiato.conf
# --------------------------------------------------
# -- APPEARANCE & UI -------------------------------
# --------------------------------------------------
cursor_shape     block
cursor_blink_interval 0.5
window_margin_width 5

# --------------------------------------------------
# -- FUNCTIONALITY ---------------------------------
# --------------------------------------------------
scrollback_lines 10000
allow_remote_control yes
listen_on unix:/tmp/kitty

# --------------------------------------------------
# -- KEYMAPS ---------------------------------------
# --------------------------------------------------
# map ctrl+shift+u open_url_with_default_browser
map ctrl+shift+k clear_terminal scrollback active

tab_bar_min_tabs            1
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}


# BEGIN_KITTY_THEME
# END_KITTY_THEME
